services:
  postgres:
    image: postgres:16
    container_name: foodeals-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foodealsclient
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - foodeals_pg:/var/lib/postgresql/data

volumes:
  foodeals_pg:
